language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
      env: SYMFONY_VERSION=^3.4
    - php: 7.0
      dist: xenial
      env: SYMFONY_VERSION=^3.4
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^3.4
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^3.4
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^3.4
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^3.4
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^5.0

before_install: travis_retry composer require "symfony/process:${SYMFONY_VERSION}" --no-update

install: travis_retry composer install --prefer-dist --no-progress -n -o

script: vendor/bin/phpunit
